language: c
compiler:
  - gcc
  - clang
env:
  - CONFIG_OPT="--disable-pthread"
  - CONFIG_OPT="--enable-pthread"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gengetopt docbook-xsl xsltproc libcunit1-dev bc lynx
  - sudo pip install cpp-coveralls
  - autoconf
  - autoheader
install:
  - ./configure --enable-tests --enable-coverage $CONFIG_OPT
  - make
script :
  - make --quiet test
after_success:
  - coveralls --gcov-options '\-lp' --exclude src/unit
