language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gengetopt gperf docbook-xsl xsltproc libcunit1-dev bc
  - autoconf
  - autoheader
install:
  - ./configure --enable-tests
  - make
  - sudo make install
script :
  - make --quiet test
