language: c
compiler:
  - gcc
  - clang
env:
  - CONFIG_OPT="--disable-pthread"
  - CONFIG_OPT="--enable-pthread"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gengetopt docbook-xsl xsltproc libcunit1-dev bc
  - autoconf
  - autoheader
install:
  - ./configure --enable-tests $CONFIG_OPT
  - make
  - make install
script :
  - make --quiet test
