.\" J.J.Green
.\" $Id: gfs2xyz.1,v 1.1 2007/11/13 23:57:54 jjg Exp jjg $
.TH GFS2XYZ 1 "13 Nov 2007"

.SH NAME
.B gfs2xyz
- dump scalar octree data in gerris (gfs) files to uniform
grids in ascii columns.

.SH SYNOPSIS
.B gfs2xyz
[
.B \-h
]
[
.B \-i
]
[
.BI \-o\  file
]
[
.BI \-s\  variable
]
[
.B \-v
]
[
.B \-V
]
.I file

.SH DESCRIPTION
.P
The 
.B gfs2xyz
reads gts files produced by 
.BR gerris2D (1) 
simulations and writes scalar fields defined in them to 
a uniform grid, as 
.IR x , 
.IR y , 
.I z
ascii column data.

Such output data can be processed with many other programs,
in particular the 
.BR GMT (1)
suite of plotting programs. Users of 
.BR xyz2grd (1)
should note that the grid is pixel registered. [check] 

.SH OPTIONS

.TP
.B \-h,\ \-\-help
Brief help.

.TP
.B \-i,\ \-\-index
Write the 
.IR i ,
.I j
indices instead of 
.IR x , 
.I y  
values.

.TP
.BI \-o,\ \-\-output\  file
Plot output to 
.I file
rather than standard output.

.TP
.BI \-s,\ \-\-scalar\  name
Specify the scalar quantity to extract from the file. 
The argument can be a
.I GtsVariable
such as "Vorticity", or a
.I GtsFunction 
such as "(Vorticity/2.0 + U)". In the latter case take
care to quote shell metacharacters.

.TP
.B \-v,\ \-\-verbose
Verbose operation.

.TP
.B \-V,\ \-\-version
Version information.

.SH EXAMPLES

To extract the scalar field Vorticity from the simulation 
frame-2.0.grs
.IP
.B  gfs2xys
.B  \-v
.BR \-s\  Vorticity 
.BR \-o\  v1.dat
.R  frame-2.0.dat 
.LP
Likewise, but extractng a function of the variables
.IP
.B  gfs2xys
.B  \-v
.BR \-s\  \'(0.5\ *\ (U\ +\ V))\' 
.BR \-o\  v2.dat
.R  frame-2.0.dat 
.LP

.SH AUTHOR
J.J. Green, University of Sheffield.

.SH "SEE ALSO"
.BR gerris2D (1),
.BR GMT (1),
.BR xyz2grd (1).


